### ISSUE TITLE
Not connecting to char after version update

### ISSUE THREAD

**Issue by queenhawk** [DanielHazzard/Cure-Please#119]
Using Windower, it is not connecting to a character or detecting party after Nov. version update, therefore having no functionality.

**Comment by camosaan** [comment]
Pulled latest EliteMMO files to be sure, tried manually loading addon with no success.

Seems as though there's been a change to PIDs and it can't parse them/attach to them. I'm not that samiliar with your code @DanielHazzard but it looks like it's going to need an update to the EliteMMO components rather than in CP itself, seems to be a similar story across the board with other dependant apps (EasyFarm etc).

**Comment by Drorond** [comment]
I have the same issue, cant detect PL or monitored player.

**Comment by Stunna-Bih** [comment]
Yeah im having the same Issue Cure me please is not detecting players or the PL after the update

**Comment by DanielHazzard** [comment]
EliteAPI will need to be updated to account for changes., I'll update this issue when the creator has updated.

**Comment by DanielHazzard** [comment]
EliteAPI has been partially fixed, though a final fix has yet to be released. When a final fix is released I'll update the main programs release with it.

For those that do not wish to wait I've included the partial fix as a .ZIP file attachment. (Thank you atom0s for the work you do.)

[EliteAPI_NotFinal.zip](https://github.com/DanielHazzard/Cure-Please/files/5520757/EliteAPI_NotFinal.zip)
