### ISSUE TITLE
Cure Please Still not letting you Select Characters

### ISSUE THREAD

**Issue by Stunna-Bih** [DanielHazzard/Cure-Please#121]

**Comment by edavis317** [comment]
I am additionally having an issue of it not selecting. Tried reinstalling but it wont select and operate. This happened after yesterdays update

**Comment by kylouie1616** [comment]
I had the same issue you guys did, the issue is you need to update a single file called EliteAPI.dll
here is the link the creator of cureplease gave me to update this file.
http://ext.elitemmonetwork.com/downloads/eliteapi/
Everything that is causing you an issue 100% has to do with this file.  If it still doesn't work after you replace the file you currently have with the one in the link above then you haven't really replaced it yet.  I actually had to delete my original file and then when I placed the "new" updated one in the folder it started working again.

Hope this helps

**Comment by minipeewee** [comment]
Same thing happened to me after the update. Tried replacing the eliteapi file but still doesn't work.

**Comment by edavis317** [comment]
@kylouie1616 That did it, thanks! I had to remove the old one before replacing.
