### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by darkchylde01** [DanielHazzard/Cure-Please#23]
I have a issue I’m trying to set up cure me myself but not sure how to is there a guide somewhere that can assist me on doing this

**Comment by DanielHazzard** [comment]
Not yet, I'm in the process of writing one after I've seen so much incorrect guides being released.

**Comment by darkchylde01** [comment]
With the whole thing extracting files what folder to put it in. I tried looking up but can’t find

**Comment by DanielHazzard** [comment]
You extract it with a ZIP extraction program, WinZip WinRar etc

It can go in any folder, however you have to move the CurePlease_addon folder to the Ashita/Plugins or Windower/Plugins directory.

**Comment by darkchylde01** [comment]
THank you going to try when I get home

**Comment by darkchylde01** [comment]
hey so i downloaded and extracted the file, then pasted the file into windowers addon section, but now how do i use it to bot my whm?

**Comment by darkchylde01** [comment]
heres where i am, i downloaded the cure please zip (top file) and extracted it using winzip, copied the file and pasted it in the addon folder. where do i go from here? and where do i find or make the luas to turn my whm into a bot? thanks in advance

**Comment by DanielHazzard** [comment]
After extracting all files and placing the CurePlease_Addon LUA into your addon folder, login to your WHM account once you are fully logged in, Open CurePlease.EXE.

You'll now see the CurePlease main screen, first steps first you need to activate CurePlease on your character/s so Select your character from the COMBO BOX next to the label titled: Selected PL: NONE and click the Select button, the Selected PL: NONE should now change to Selected PL: Your character.

If you have another character, such as a tank or melee then do the same step for Monitored Player: NONE but select them. Once this is done the characters will now be linked, Click the PAUSE button to pause all actions temporarily.

Now you must set what you want enabled and all settings etc.... So near the top on the Toolbar click Options. This will open the options tabs. Now activate any and all options you want enabled in the tabs in this page. Some will show a help text if you hover over them for a few seconds.

Once you've selected them all I strongly suggest you save them to an XML file by clicking the Save as... button, and NOT the Save All Settings as they will only save while the bot is open.

Note: FFXI will crash when loading CurePlease if you have your UAC set to dim the screen due to PlayOnline being a older game, simply drop the UAC down one level so it doesn't dim the screen.

**Comment by darkchylde01** [comment]
Thanks so much got it working
